"""Initial table created

Revision ID: 7ec41f55ee8c
Revises: fec1b1a3a1c4
Create Date: 2025-02-12 17:00:08.012239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ec41f55ee8c"
down_revision: Union[str, None] = "fec1b1a3a1c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
